### ISSUE TITLE
Chaining issue with wrap()

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#90]
This snippet works fine:
```js
match(function() { return this.ctx.side === 'left'; }).wrap()(function() {
    return [this.ctx, {elem: 'box'}];
})
```
but with `bem-xjst@4.0.1` it's impossible to switch `wrap()` with `match()` like this:

```js
wrap().match(function() { return this.ctx.side === 'left'; })(function() {
    return [this.ctx, {elem: 'box'}];
})
```

Both variants work fine with `bem-xjst@1.2.1` though.

**Comment by indutny** [comment]
@tadatuta what JSON reproduces the problem?

**Comment by tadatuta** [comment]
For
```js
{
    block: 'b1',
    key: 'val'
}
```
with
```js
block('b1')(
    wrap().match(function() { return this.ctx.key; })(function() {
        return {
            block: 'b2',
            content: this.ctx
        };
    })
);
```
the result is
```
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/tadatuta/Sites/pr-stub-bemxjst/desktop.bundles/index/index.bemhtml.js:1728:12)
    at Tree.build (/Users/tadatuta/Sites/pr-stub-bemxjst/desktop.bundles/index/index.bemhtml.js:1354:13)
    at BEMHTML.compile (/Users/tadatuta/Sites/pr-stub-bemxjst/desktop.bundles/index/index.bemhtml.js:340:18)
    at __bem_xjst (/Users/tadatuta/Sites/pr-stub-bemxjst/desktop.bundles/index/index.bemhtml.js:1725:5)
    at /Users/tadatuta/Sites/pr-stub-bemxjst/desktop.bundles/index/index.bemhtml.js:1747:26
    at Object.<anonymous> (/Users/tadatuta/Sites/pr-stub-bemxjst/desktop.bundles/index/index.bemhtml.js:1757:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

with
```js
block('b1')(
    match(function() { return this.ctx.key; }).wrap()(function() {
        return {
            block: 'b2',
            content: this.ctx
        };
    })
);
```
everything is ok.

**Comment by indutny** [comment]
Fixed! Looks like `extend()`/`replace()` never worked this way either. Even in 1.x

**Comment by indutny** [comment]
Oh, btw `wrap()` probably doesn't work like this in dev mode of v1.x, I wouldn't rely much on it.
